# Generated by Django 5.2.7 on 2025-12-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0002_alter_news_content_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название дела')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Номер дела')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
                ('content', models.TextField(verbose_name='Описание дела')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('closed', 'Закрыто'), ('pending', 'На рассмотрении'), ('appeal', 'Апелляция')], default='pending', max_length=20, verbose_name='Статус дела')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата принятия дела')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('court_documents', models.FileField(blank=True, upload_to='court_docs/%Y/%m/%d/', verbose_name='Судебные документы')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Конфиденциальное дело')),
            ],
            options={
                'verbose_name': 'Судебное дело',
                'verbose_name_plural': 'Судебные дела',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название области практики')),
                ('description', models.TextField(blank=True, verbose_name='Описание области практики')),
            ],
            options={
                'verbose_name': 'Область практики',
                'verbose_name_plural': 'Области практики',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='case',
            name='practice_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lex.practicearea', verbose_name='Область практики'),
        ),
    ]
