# Generated by Django 5.2.7 on 2025-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/%Y/%m/%d/', verbose_name='Изображение новости'),
        ),
    ]
